name= input("Ingrese las 2 primera letras de su nombre: ")
lastName= input("Ingrese las 2 primeras letras de su apellido: ")
rut= input("Ingrese los 2 primeros numeros de su RUT: ")
month= input("Ingrese las 3 primeras letras del mes de nacimiento: ")
city= input("Ingresa las ultimas letras de la ciudad donde vives: ")
print("")
opcion_1= print(name+lastName+rut+month+city)
opcion_2= print(name+rut+lastName+month+city+month)
opcion_3= print(rut+name+month+city+lastName)
opcion_4= print(lastName+rut+name+month+city+rut)
opcion_5= print(city+lastName+name+rut+month+city)
